config/routes.rb
require "monban/constraints/signed_in"
require "monban/constraints/signed_out"

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end

  constraints Monban::Constraints::SignedOut.new do
    root "landings#show"
  end

  resources :categories, only: [:create]
  resources :locations, only: [:index, :create, :show] do
    resources :categories, only: [:show]
  end

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :categories, only: [:index, :create, :show]
  resources :posts, only: [:edit, :index, :new, :create, :destroy, :show]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts

  validates :name, presence: true, uniqueness: true


end

app/models/dashboard.rb
class Dashboard
  attr_reader :categories, :locations, :user

  def initialize(user, locations = Location.all, categories = Category.all)
    @locations = locations
    @categories = categories
    @user = user
  end

  def location
    Location.new
  end

  def category(*args)
    Category.new(*args)
  end

  def user_email
    @user.email
  end

  def categories_names
    @categories.map { |category| category.name }
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :posts

  validates :name, presence: true
  validates :state, presence: true
  validates_uniqueness_of :name, scope: :state
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :location
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category saved successfully"
    else
      flash[:error] = "Category did not save"
    end
    redirect_to :back
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @dashboard = Dashboard.new(current_user)

    if @dashboard.user.admin
      render :admin
    end
  end

  def admin
  end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def show
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def create
    @location=Location.create(location_params)
    redirect_to root_path
  end

  def show
    @location = Location.find(params[:id])
  end

  def index
    @locations = Location.all
  end

  private

  def location_params
    params.require(:location).permit(:name, :state)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      flash[:notice] = "Post saved successfully"
      render :show
    else
      flash[:error] = "Post did not save"
      redirect_to :back
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to [@post.category, @post]
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy

    redirect_to category
  end


  private

  def post_params
    params.require(:post).permit(
      :category_id,
      :content,
      :location_id,
      :title,
    ).merge(user: current_user)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @post = TextShout.where("body ILIKE ?", "%#{params[:query]}%")
    @shouts=Shout.where(content_type: "TextShout", content_id: @text_shouts.pluck(:id))
    @users=User.where("email ILIKE ?", "%#{params[:query]}%")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<li><%=link_to category.name, [location, category]%></li>

app/views/categories/index.html.erb
<h1>Categories</h1>

<section>
  <ol>
    <%= render @categories %>
  </ol>
</section>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>

<hr>

<section>
  <%= link_to "Create New Post", new_post_path(
    @post,
    category_id: params[:id],
    location_id: params[:location_id]) %>
</section>

app/views/dashboards/admin.html.erb
<h1> Admin Dashboard Page </h1>
<p> Welcome <%= @dashboard.user_email %>! </p>

<hr>

<section>
  <h3>Current Locations</h3>
  <ol>
    <% @dashboard.locations.each do |location| %>
      <li>
        <%= link_to "#{location.name}", location_path(location) %>
      </li>
    <% end %>
  </ol>

  <h3>Add Location</h3>

  <%= form_for @dashboard.location do |form|%>
    <div>
      <%= form.label :name, "City:  "%>
      <%= form.text_field :name %>
    </div>
    <div>
      <%= form.label :state, "State: "%>
      <%= form.text_field :state %>
      <%= form.submit %>
    </div>
    <% end %>
</section>

<hr>

<section>
  <h3>Current Categories</h3>
  <ol>
    <% @dashboard.categories_names.each do |name| %>
      <li><%= name %></li>
    <% end %>
  </ol>

  <h3>Add Category</h3>
  <%= form_for @dashboard.category do |form| %>
    <%= form.label :name, "Category Name: " %>
    <%= form.text_field :name %>
    <%= form.submit %>
  <% end %>
</section>

<%@locations.each do |location|%>
  <div>
  <%=link_to "#{location.name}", location %>
  </div>
<%end%>

app/views/dashboards/show.html.erb
<h1> Dashboards page </h1>

<p> Welcome <%= @dashboard.user_email %><p>
<p> Here are your posts: </p>

<%=link_to "Locations", locations_path %>

app/views/landings/show.html.erb
<h1> Landings Page </h1>
<p> This page should have the things that people who haven't logged in can see. </p>
<p> perhaps a list of locations </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MetisCraigstr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<% if signed_in? %>
  <%= link_to "Sign out", session_path, method: :delete %>
<% else %>
  <%= link_to "Sign in", new_session_path %>
  <%= link_to "Sign up", new_user_path %>
<% end %>

<p>
<% flash.each do | message | %>
  <%= message %>
<% end %>
</p>

<%= yield %>

</body>
</html>

app/views/locations/index.html.erb
  <h1> Locations index</h1>
  <ol>
    <%@locations.each do |location|%>
      <li>
        <%=link_to "#{location.name}", location_path(location) %>
      </li>
    <%end%>
  </ol>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>

<section>
  <%= render Category.all, location: @location %>
</section>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="form_post">
    <%= f.label :title %>
    <%= f.text_field :title%>
  </div>

  <div class="form_post">
  <%= f.label :category %>
  <%= f.text_field :category %>
  </div>

  <div class="form_post">
    <%= f.label :location %>
    <%= f.text_field :location%>
  </div>

  <div class="form_post">
    <%= f.label :content %>
    <%= f.text_area :content%>
  </div>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>posts</h1>

<%= render partial: 'list', locals: { posts: @posts } %>

app/views/posts/new.html.erb
<h1>New post</h1>

<section>
  <h3>Add New Post</h3>

  <%= form_for @post do |f| %>
    <div class="form_post">
      <%= f.label :title %>
      <%= f.text_field :title%>
    </div>

    <div class="form_post">
      <%= f.hidden_field :category_id, value: params[:category_id] %>
      <%= f.hidden_field :location_id, value: params[:location_id] %>
    </div>

    <div class="form_post">
      <%= f.label :content %>
      <%= f.text_area :content%>
      <%= f.submit %>
    </div>
  <% end %>
</section>

app/views/posts/show.html.erb
<div>
  <strong>Title:</strong>
  <%= @post.title %>
</div>

<div>
  <strong>Description:</strong>
  <%= @post.content %>
</div>

<div>
  <strong>Category:</strong>
  <%= @post.category.name %>
</div>

<div>
  <strong>Location:</strong>
  <%= @post.location.name %>
</div>

<div>
  <strong>User:</strong>
  <%= @post.user.email %>
</div>

<section>
  <%= link_to "Edit Post", edit_post_path(@post) %>
  <%= link_to "Delete Post",
    @post,
    method: :delete,
    data: { confirm: "Are you sure?" } %>
</section>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form_for @user, :url => users_path, :html => { :multipart => true } do |form| %>
    <%= form.file_field :avatar %>
  </div>
<% end %>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>